name: Deploy to AWS S3

on:
  pull_request:
    types: [closed]
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    if: github.event.pull_request.merged

    steps:
      - name: Checkout this repo
        uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependency
        run: yarn install

      - name: Build
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
        run: yarn build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: yarn deploy
